POST http://localhost:55578/api/v1/admin/pages/demo
Content-Type: application/json

{
    "descriptor": {
        "name": "new_page"
    },
    "title": {
        "de": "Neue Seite",
        "en": "New page"
    },
    "active": false
}

###

DELETE http://localhost:55578/api/v1/admin/pages/demo/a6bc02ae-9a89-44b5-b3c0-678541b1db54

###

POST http://localhost:55578/api/v1/admin/pages/demo/clone/demo.index

###

PUT http://localhost:55578/api/v1/admin/pages/demo/85bb9417-5493-4ef4-9aad-610599e0488b
Content-Type: application/json

{
    "active": true
}

###
