##
## Create page
##

# parentId : String
# title : Map<String, String>*
# showInMainNavigation : Boolean
# showInTopNavigation : Boolean
# showInFooterNavigation : Boolean
# afterPageId : String

POST http://localhost:55578/api/v1/backend/pages/demo
Content-Type: application/json

{
    "title": {
        "de": "New"
    },
    "showInMainNavigation": true,
    "navigationEntry": false,
    "media": false,
    "external": false,
    "href": ""
}

###

##
## Update page
##

# topNavigationTitle : Map<String, String>
# mainNavigationTitle Map<String, String>
# footerNavigationTitle Map<String, String>
# showInMainNavigation Boolean
# showInTopNavigation Boolean
# showInFooterNavigation Boolean
# active Boolean

PUT http://localhost:55578/api/v1/backend/pages/demo/6ad3d8e7-5717-4845-bdbe-0ddad1454222
Content-Type: application/json

{
    "title": {
        "de": "Neu",
        "en": "New"
    },
    "showInTopNavigation": false,
    "showInFooterNavigation": false,
    "navigationEntry": false,
    "media": false,
    "external": false,
    "href": "",
    "active": true
}

###

##
## Clone page
##

POST http://localhost:55578/api/v1/backend/pages/demo/clone/index

###

##
## Delete page
##

DELETE http://localhost:55578/api/v1/backend/pages/demo/59f624af-5009-4591-b78d-5c97e847f44d

###
