##
## Create user group
##

# name : Map<String, String>*

POST http://localhost:55578/api/v1/backend/sites/demo/user-groups
Content-Type: application/json

{
    "name": {
        "de": "Mitarbeiter",
        "en": "Employee"
    }
}

###

##
## Create user
##

# email : String*
# salutation : String
# title : String
# firstName : String
# lastName : String
# company : String
# street : String
# postalCode : String
# city : String
# phone : String
# mobile : String
# fax : String
# country : String
# groups : String[]

POST http://localhost:55578/api/v1/backend/sites/demo/users
Content-Type: application/json

{
    "email": "schofield+aaa@cominto.de"
}

###

PUT http://localhost:55578/api/v1/backend/sites/demo/users/c2a09acd-33a2-4000-8dcd-0c433ba19062
Content-Type: application/json

{
    "company": ""
}

###

DELETE http://localhost:55578/api/v1/backend/sites/demo/users/c2a09acd-33a2-4000-8dcd-0c433ba19062

###
